### ISSUE TITLE
Test broken in master

### ISSUE THREAD

**Issue by gianarb** [zendframework/ZFTool#103]
Hi! I'm trying to fix issue #99 but this test is broken in master branch
https://github.com/zendframework/ZFTool/blob/master/tests/ZFToolTest/Model/SkeletonTest.php#L60
because Skeleton::exportConfig($config) don't return a string but a different array.

https://github.com/zendframework/ZFTool/blob/master/src/ZFTool/Model/Skeleton.php#L84-86

**Comment by snapshotpl** [comment]
@gianarb is fixed in master branch

**Comment by ezimuel** [comment]
@gianarb I fixed the issue, the behaviour of Skeleton::exportConfig($config) is changed in the meantime. I casted to string and adapted to the new output here: https://github.com/zendframework/ZFTool/blob/master/tests/ZFToolTest/Model/SkeletonTest.php#L60

**Comment by gianarb** [comment]
Thanks!
