### ISSUE TITLE
Missing require dependency for Zend\Log in composer.json

### ISSUE THREAD

**Issue by Martin-P** [zendframework/ZFTool#106]
I created `zftool.phar` by executing the following command:
```
$ php create-phar
Phar created successfully in D:\path-to\vendor\zendframework\zftool\bin/zftool.phar
```

Next I tried to run:
```
php zftool.phar
```
Result:
```
Fatal error: Class 'Zend\Log\ProcessorPluginManager' not found in phar://D:/path-to/vendor/zendframework/zftool/bin/zftool.phar/vendor/zendframework/zend-mvc/Zend/Mvc/Service/AbstractPluginManagerFactory.php on line 2
```

It seems `Zend\Log` is missing in `composer.json`. After adding it, running `composer update` and again running `php create-phar` everything works fine.

**Suggested fix**:
Add this line to the `require` section of `composer.json`:
```
"zendframework/zend-log": ">=2.2.2",
```

**Comment by Martin-P** [comment]
Just to be sure: is anyone maintaining ZFTool or did I create a new issue on a dead project? :disappointed:

**Comment by Ocramius** [comment]
I think @ezimuel is assigned to this project.

**Comment by stevleibelt** [comment]
@Martin-P 
Error still exsist, thanks for your fix - I could solve this issue by patching your missing dependency into my composer.conf :+1: 

Kind Regards

**Comment by Martin-P** [comment]
No problem, glad it helped you fix the issue :smiley: 

Ping @Ocramius @ezimuel @weierophinney 
Looking at the lack of response, I still get the feeling nobody is maintaining this repository. Can someone check internally who is responsible for this repository and bring this tool back to life? If nobody is responsible or any support for this tool has come to a halt, please update the description and readme file so people know for a fact they are contributing to a dead project. Thanks!

**Comment by RalfEggert** [comment]
@Martin-P 

Here is a comment from Matthew regarding the current status of ZFTool:

https://github.com/zendframework/ZFTool/issues/101#issuecomment-63518623

It would be nice to add this to the description. 

I am currently working on a rewrite based on https://github.com/zfcampus/zf-console in my spare time but it is not ready for take off yet.

**Comment by ezimuel** [comment]
I fixed this issue in the last merge. There was missing dependencies to Zend\Log and Zend\I18n due to the last Zend\Mvc implementations.
