### ISSUE TITLE
zftool.phar: command not found

### ISSUE THREAD

**Issue by alirahnema** [zendframework/ZFTool#114]
i download the zftool.phar and copy it to vendor/ZFtool and when go to that folder on ubuntu system it say: zftool.phar: command not found

**Comment by gianarb** [comment]
Hi!
Try with 
```
php ./zftool.php
```
if you are into the same dir of zftool :)

**Comment by gianarb** [comment]
@alirahnema work?

**Comment by ezimuel** [comment]
@alirahnema I'm closing this issue because no reply since May 15.
