### ISSUE TITLE
Create action doesn't work

### ISSUE THREAD

**Issue by Romano83** [zendframework/ZFTool#116]
Hello!
When I trying to create an action with ZFTool *e.g*  `zf.php create action add Index Console z:/zend/app`, I add this error : `Invalid arguments or no arguments provided`.
I also trying with `zf.php create action add IndexController Console z:/zend/app`.
For informations, my working environment is under Windows 7 and the *IndexController* and the *Console* module were previously created with ZFTool...

**Comment by gianarb** [comment]
Hi!
The entrypoint command is 
`create action <name> <controllerName> <module>`

**Comment by Romano83** [comment]
Yes you're right ! 
I've try with this entrypoint command and it's seems to work. However when I add the optional path argument, I have this error...
Maybe it's comes from my dev enviroment...
I think I can close this issue.
Thanks a lot !
