### ISSUE TITLE
ZFTool keeps saying it has thrown an exception when no exception is listed.

### ISSUE THREAD

**Issue by Toltar** [zendframework/ZFTool#130]
Hello. I have tried to use the ZFTool and I get this strange error where it says it throws an exception, but it lists no exception. I was wondering if anyone can help me with this.  I have seen the issue in issues #62 although it seems while the issue has been closed and unresolved. Here is a screenshot:
![zftoolerror](https://cloud.githubusercontent.com/assets/6003536/16491027/ca90d840-3ea1-11e6-88fd-27ace1b67fbb.png)

This seems to happen no matter what command I enter. If anyone needs further clarification of anything please let me know. And I thank everyone in advance for their time and help to the issue.

### System Specifications
* OS: OSX 10.11
* PHP Version: 5.6
* Zend Framework Version: 2.3.1

**Comment by kifarre** [comment]
can you try to desactivate all modules ?
 in your application.config.php
    'modules' => array(
        'Application',
    ),
 or modules.config.php (if exists)
return [
    'Application',
];

when i have some problemes in a module, i can't use ZendTool.

**Comment by Toltar** [comment]
Sorry I forgot to let you know that I have successfully solved this issue. I tried just creating a new Zend Project and it worked. I am not sure exactly how I fixed it because I fixed it a month ago, but for now I will close this issue till this comes up again.
