### ISSUE TITLE
What is the license of this project?

### ISSUE THREAD

**Issue by gartner** [zendframework/ZFTool#139]
I am using ZF3 now, but I miss the diagnostics-functionality from ZFTool.
So, I made a fork of this repository, and I made some changes to make diagnostics work on Zend Framework 3: https://github.com/gartner/ZFTool

All the code generating stuff from ZFTool is still not working in my fork, and I don't think I will fix these.
So, I'm thinking of making a new module, call it something else than ZFTool (palustris/diagnostics most likely), but it will still mostly be the code from the DiagnosticsController from ZFTool.

But will the license allow me to do that?

**Comment by froschdesign** [comment]
@gartner 
> But will the license allow me to do that?

Please look at the `composer.json` file:

```json
"license": "BSD-3-Clause",
```

https://github.com/zendframework/ZFTool/blob/master/composer.json#L9

https://opensource.org/licenses/BSD-3-Clause

**Comment by gartner** [comment]
Doh! Thanks for the pointer, obvious a place I should have looked. I was looking for a LICENSE-file or something.
