### ISSUE TITLE
Error install composer

### ISSUE THREAD

**Issue by guilherme90** [zendframework/ZFTool#140]
I trying run command `composer require --dev zendframework/zftool:dev-master` and return this error:

` Problem 1
    - zendframework/zend-json 2.4.9 requires zendframework/zend-stdlib 2.4.9 -> satisfiable by zendframework/zend-stdlib[2.4.9] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.4.8 requires zendframework/zend-stdlib 2.4.8 -> satisfiable by zendframework/zend-stdlib[2.4.8] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.4.7 requires zendframework/zend-stdlib 2.4.7 -> satisfiable by zendframework/zend-stdlib[2.4.7] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.4.6 requires zendframework/zend-stdlib 2.4.6 -> satisfiable by zendframework/zend-stdlib[2.4.6] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.4.5 requires zendframework/zend-stdlib 2.4.5 -> satisfiable by zendframework/zend-stdlib[2.4.5] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.4.4 requires zendframework/zend-stdlib 2.4.4 -> satisfiable by zendframework/zend-stdlib[2.4.4] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.4.3 requires zendframework/zend-stdlib 2.4.3 -> satisfiable by zendframework/zend-stdlib[2.4.3] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.4.2 requires zendframework/zend-stdlib 2.4.2 -> satisfiable by zendframework/zend-stdlib[2.4.2] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.4.13 requires zendframework/zend-stdlib 2.4.13 -> satisfiable by zendframework/zend-stdlib[2.4.13] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.4.12 requires zendframework/zend-stdlib 2.4.12 -> satisfiable by zendframework/zend-stdlib[2.4.12] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.4.11 requires zendframework/zend-stdlib 2.4.11 -> satisfiable by zendframework/zend-stdlib[2.4.11] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.4.10 requires zendframework/zend-stdlib 2.4.10 -> satisfiable by zendframework/zend-stdlib[2.4.10] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.4.1 requires zendframework/zend-stdlib 2.4.1 -> satisfiable by zendframework/zend-stdlib[2.4.1] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.4.0 requires zendframework/zend-stdlib 2.4.0 -> satisfiable by zendframework/zend-stdlib[2.4.0] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.3.9 requires zendframework/zend-stdlib 2.3.9 -> satisfiable by zendframework/zend-stdlib[2.3.9] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.3.8 requires zendframework/zend-stdlib 2.3.8 -> satisfiable by zendframework/zend-stdlib[2.3.8] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.3.7 requires zendframework/zend-stdlib 2.3.7 -> satisfiable by zendframework/zend-stdlib[2.3.7] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.3.6 requires zendframework/zend-stdlib 2.3.6 -> satisfiable by zendframework/zend-stdlib[2.3.6] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.3.5 requires zendframework/zend-stdlib 2.3.5 -> satisfiable by zendframework/zend-stdlib[2.3.5] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.3.4 requires zendframework/zend-stdlib 2.3.4 -> satisfiable by zendframework/zend-stdlib[2.3.4] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.3.3 requires zendframework/zend-stdlib 2.3.3 -> satisfiable by zendframework/zend-stdlib[2.3.3] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.3.2 requires zendframework/zend-stdlib 2.3.2 -> satisfiable by zendframework/zend-stdlib[2.3.2] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.3.1 requires zendframework/zend-stdlib 2.3.1 -> satisfiable by zendframework/zend-stdlib[2.3.1] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.3.0 requires zendframework/zend-stdlib 2.3.0 -> satisfiable by zendframework/zend-stdlib[2.3.0] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.2.9 requires zendframework/zend-stdlib 2.2.9 -> satisfiable by zendframework/zend-stdlib[2.2.9] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.2.8 requires zendframework/zend-stdlib 2.2.8 -> satisfiable by zendframework/zend-stdlib[2.2.8] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.2.7 requires zendframework/zend-stdlib 2.2.7 -> satisfiable by zendframework/zend-stdlib[2.2.7] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.2.6 requires zendframework/zend-stdlib 2.2.6 -> satisfiable by zendframework/zend-stdlib[2.2.6] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.2.5 requires zendframework/zend-stdlib 2.2.5 -> satisfiable by zendframework/zend-stdlib[2.2.5] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.2.4 requires zendframework/zend-stdlib 2.2.4 -> satisfiable by zendframework/zend-stdlib[2.2.4] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.2.3 requires zendframework/zend-stdlib 2.2.3 -> satisfiable by zendframework/zend-stdlib[2.2.3] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.2.2 requires zendframework/zend-stdlib 2.2.2 -> satisfiable by zendframework/zend-stdlib[2.2.2] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.2.10 requires zendframework/zend-stdlib 2.2.10 -> satisfiable by zendframework/zend-stdlib[2.2.10] but these conflict with your requirements or minimum-stability.
    - zendframework/zend-json 2.5.0 requires zendframework/zend-stdlib ~2.5.0 -> satisfiable by zendframework/zend-stdlib[2.5.0, 2.5.1, 2.5.2] but these conflict with your requirements or minimum-stability.`

` - zendframework/zend-version 2.4.9 requires zendframework/zend-json 2.4.9 -> satisfiable by zendframework/zend-json[2.4.9].
    - zendframework/zend-version 2.4.8 requires zendframework/zend-json 2.4.8 -> satisfiable by zendframework/zend-json[2.4.8].
    - zendframework/zend-version 2.4.7 requires zendframework/zend-json 2.4.7 -> satisfiable by zendframework/zend-json[2.4.7].
    - zendframework/zend-version 2.4.6 requires zendframework/zend-json 2.4.6 -> satisfiable by zendframework/zend-json[2.4.6].
    - zendframework/zend-version 2.4.5 requires zendframework/zend-json 2.4.5 -> satisfiable by zendframework/zend-json[2.4.5].
    - zendframework/zend-version 2.4.4 requires zendframework/zend-json 2.4.4 -> satisfiable by zendframework/zend-json[2.4.4].
    - zendframework/zend-version 2.4.3 requires zendframework/zend-json 2.4.3 -> satisfiable by zendframework/zend-json[2.4.3].
    - zendframework/zend-version 2.4.2 requires zendframework/zend-json 2.4.2 -> satisfiable by zendframework/zend-json[2.4.2].
    - zendframework/zend-version 2.4.13 requires zendframework/zend-json 2.4.13 -> satisfiable by zendframework/zend-json[2.4.13].
    - zendframework/zend-version 2.4.12 requires zendframework/zend-json 2.4.12 -> satisfiable by zendframework/zend-json[2.4.12].
    - zendframework/zend-version 2.4.11 requires zendframework/zend-json 2.4.11 -> satisfiable by zendframework/zend-json[2.4.11].
    - zendframework/zend-version 2.4.10 requires zendframework/zend-json 2.4.10 -> satisfiable by zendframework/zend-json[2.4.10].
    - zendframework/zend-version 2.4.1 requires zendframework/zend-json 2.4.1 -> satisfiable by zendframework/zend-json[2.4.1].
    - zendframework/zend-version 2.4.0 requires zendframework/zend-json 2.4.0 -> satisfiable by zendframework/zend-json[2.4.0].
    - zendframework/zend-version 2.3.9 requires zendframework/zend-json 2.3.9 -> satisfiable by zendframework/zend-json[2.3.9].
    - zendframework/zend-version 2.3.8 requires zendframework/zend-json 2.3.8 -> satisfiable by zendframework/zend-json[2.3.8].
    - zendframework/zend-version 2.3.7 requires zendframework/zend-json 2.3.7 -> satisfiable by zendframework/zend-json[2.3.7].
    - zendframework/zend-version 2.3.6 requires zendframework/zend-json 2.3.6 -> satisfiable by zendframework/zend-json[2.3.6].
    - zendframework/zend-version 2.3.5 requires zendframework/zend-json 2.3.5 -> satisfiable by zendframework/zend-json[2.3.5].
    - zendframework/zend-version 2.3.4 requires zendframework/zend-json 2.3.4 -> satisfiable by zendframework/zend-json[2.3.4].
    - zendframework/zend-version 2.3.3 requires zendframework/zend-json 2.3.3 -> satisfiable by zendframework/zend-json[2.3.3].
    - zendframework/zend-version 2.3.2 requires zendframework/zend-json 2.3.2 -> satisfiable by zendframework/zend-json[2.3.2].
    - zendframework/zend-version 2.3.1 requires zendframework/zend-json 2.3.1 -> satisfiable by zendframework/zend-json[2.3.1].
    - zendframework/zend-version 2.3.0 requires zendframework/zend-json 2.3.0 -> satisfiable by zendframework/zend-json[2.3.0].
    - zendframework/zend-version 2.2.9 requires zendframework/zend-json 2.2.9 -> satisfiable by zendframework/zend-json[2.2.9].
    - zendframework/zend-version 2.2.8 requires zendframework/zend-json 2.2.8 -> satisfiable by zendframework/zend-json[2.2.8].
    - zendframework/zend-version 2.2.7 requires zendframework/zend-json 2.2.7 -> satisfiable by zendframework/zend-json[2.2.7].
    - zendframework/zend-version 2.2.6 requires zendframework/zend-json 2.2.6 -> satisfiable by zendframework/zend-json[2.2.6].
    - zendframework/zend-version 2.2.5 requires zendframework/zend-json 2.2.5 -> satisfiable by zendframework/zend-json[2.2.5].
    - zendframework/zend-version 2.2.4 requires zendframework/zend-json 2.2.4 -> satisfiable by zendframework/zend-json[2.2.4].
    - zendframework/zend-version 2.2.3 requires zendframework/zend-json 2.2.3 -> satisfiable by zendframework/zend-json[2.2.3].
    - zendframework/zend-version 2.2.2 requires zendframework/zend-json 2.2.2 -> satisfiable by zendframework/zend-json[2.2.2].
    - zendframework/zend-version 2.2.10 requires zendframework/zend-json 2.2.10 -> satisfiable by zendframework/zend-json[2.2.10].`

`- Installation request for zendframework/zftool dev-master -> satisfiable by zendframework/zftool[dev-master].
    - Conclusion: remove zendframework/zend-json 3.0.0
    - Conclusion: don't install zendframework/zend-json 3.0.0
    - zendframework/zftool dev-master requires zendframework/zend-version >=2.2.2  -> satisfiable by zendframework/zend-version[2.2.10, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9, 2.4.0, 2.4.1, 2.4.10, 2.4.11, 2.4.12, 2.4.13, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.4.8, 2.4.9, 2.5.0, 2.5.1].
    - zendframework/zend-version 2.5.1 requires zendframework/zend-json ~2.5 -> satisfiable by zendframework/zend-json[2.5.0, 2.5.1, 2.5.2, 2.6.0, 2.6.1].
    - zendframework/zend-version 2.5.0 requires zendframework/zend-json ~2.5.0 -> satisfiable by zendframework/zend-json[2.5.0, 2.5.1, 2.5.2].
    - Can only install one of: zendframework/zend-json[2.5.1, 3.0.0].
    - Can only install one of: zendframework/zend-json[2.5.2, 3.0.0].
    - Can only install one of: zendframework/zend-json[2.6.0, 3.0.0].
    - Can only install one of: zendframework/zend-json[2.6.1, 3.0.0].
    - Installation request for zendframework/zend-json (locked at 3.0.0) -> satisfiable by zendframework/zend-json[3.0.0].`

How can i solve this problem? Thanks

**Comment by guilherme90** [comment]
Solved!

**Comment by adamlundrigan** [comment]
@guilherme90 how did you solve this?

**Comment by guilherme90** [comment]
@adamlundrigan 

remove the version `zend-json :3.0.0`, and add version ` 2.6.3`

**Comment by adamlundrigan** [comment]
:+1: The module has not (yet?) been updated to use ZF3 components

**Comment by guilherme90** [comment]
@adamlundrigan 

I'm not using ZF3. but the package `zend-json` was in the version `3.0.0`

**Comment by adamlundrigan** [comment]
It is a problem with the way version constraints are configured in this module, eg:

> "zendframework/zend-version": ">=2.2.2"

This will install zend-version 2.4.9 (since zend-version has no 3.x) which has a hard dependency on zend-json 2.x and so conflicts with you having specified zend-json 3.x in your own constraints list.

**Comment by guilherme90** [comment]
Yeah, thanks!

:)

**Comment by rminaya** [comment]
Please tell me how  you did it. write de comman you use to fix this problem
