### ISSUE TITLE
wrong autoload location if installed with composer

### ISSUE THREAD

**Issue by yurii-github** [zendframework/ZFTool#21]
when installed with composer you get error
" Error: I cannot find the autoloader of the application. "

This is because of subdirectory of zendframework. It can be resovled by adding 1 dirname to zf.php (line 17) :

$basePath = dirname(dirname(dirname($basePath)));

regards

**Comment by lubyshev** [comment]
Just run ZF from root dir:
```
$ php ./vendor/zendframework/zftool/zf.php modules list
```
