### ISSUE TITLE
Error when using ZFTool

### ISSUE THREAD

**Issue by bluebaroncompsci** [zendframework/ZFTool#51]
vagrant@precise64:/vagrant/www/ssc/ssc$ ./vendor/zendframework/zftool/zf.php create module test
PHP Fatal error:  Uncaught exception 'Zend\ModuleManager\Exception\RuntimeException' with message 'Module (ZFTool) could not be initialized.' in /vagrant/www/ssc/ssc/vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManage  r.php:175
Stack trace:
#0 /vagrant/www/ssc/ssc/vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManager.php(149): Zend\ModuleManager\ModuleManager->loadModuleByName  (Object(Zend\ModuleManager\ModuleEvent))
#1 /vagrant/www/ssc/ssc/vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManager.php(90): Zend\ModuleManager\ModuleManager->loadModule('ZFTool')
#2 [internal function]: Zend\ModuleManager\ModuleManager->onLoadModules(Object(Zend\ModuleManager\ModuleEvent))
#3 /vagrant/www/ssc/ssc/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\ModuleManager\ModuleEvent))
#4 /vagrant/www/ssc/ssc/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventM in /vagrant/www/ssc/ssc/vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManager.php on   line 175
 
Fatal error: Uncaught exception 'Zend\ModuleManager\Exception\RuntimeException'   with message 'Module (ZFTool) could not be initialized.' in /vagrant/www/ssc/ssc  /vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManager.php  :175
Stack trace:
#0 /vagrant/www/ssc/ssc/vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManager.php(149): Zend\ModuleManager\ModuleManager->loadModuleByName  (Object(Zend\ModuleManager\ModuleEvent))
#1 /vagrant/www/ssc/ssc/vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManager.php(90): Zend\ModuleManager\ModuleManager->loadModule('ZFTool')
#2 [internal function]: Zend\ModuleManager\ModuleManager->onLoadModules(Object(Zend\ModuleManager\ModuleEvent))
#3 /vagrant/www/ssc/ssc/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\ModuleManager\ModuleEvent))
#4 /vagrant/www/ssc/ssc/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventM in /vagrant/www/ssc/ssc/vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManager.php on   line 175

ssc/config/application.config.php

<?php
return array(
 'modules' => array(
  'Application',
  'ZfcBase',
  'ZfcUser',
  'Page',),
  'module_paths' => array(
   './module',
   './vendor', ),
  'config_glob_paths' => array(
   'config/autoload/{,*.}{global,local}.php',), ),
);

That's the only config that I can think might matter.  If you need to see any others, lmk.

**Comment by onelisystems** [comment]
zf.php

line 15 an16 replace by this... works
if (file_exists("$basePath/../../../vendor/autoload.php")) {
    require_once "$basePath/../../../vendor/autoload.php";

**Comment by ezimuel** [comment]
I'm closing this old issue because it's not relevant anymore.

**Comment by fallphenix** [comment]
to fixe this error, you have to make form parent directory : # php zftool.phar create module MyModule MyProject
