### ISSUE TITLE
The application has thrown an exception!

### ISSUE THREAD

**Issue by raymondelferink** [zendframework/ZFTool#62]
I have my application setup and running.

I have added zftool using composer

From the root of my application, when I run "vendor/bin/zf.php modules" it throws an exception: "The application has thrown an exception!"

I can see the same issue was briefly mentioned here: https://github.com/zendframework/ZFTool/issues/44

What can be the problem? How can I solve it?

**Comment by ezimuel** [comment]
@raymondelferink I'm closing this old issue because not relevant anymore.
