### ISSUE TITLE
PHP Fatal error:  Class 'Zend\Log\ProcessorPluginManager' 

### ISSUE THREAD

**Issue by cincarnato** [zendframework/ZFTool#92]
zftool not work. (ZF2.3.0)

step 1: 
---------------------------
Run: composer require zendframework/zftool:dev-master

and I had the problem when running :
"php zf.php"
from the directory "/vendor/zendframework/zftool"

which is where composer installed zftools in.
command line error was
"Error: I cannot find the autoloader of the application."

I try move zftool to vendor/ and same error "Error: I cannot find the autoloader of the application."

From zftool dir I try run: "composer install" and then

PHP Fatal error:  Class 'Zend\Log\ProcessorPluginManager' 
not found in /home/security/www/App/vendor/ZFTool/vendor/zendframework/zend-mvc/Zend/Mvc/Service/AbstractPluginManagerFactory.php on line 33

**Comment by paladini** [comment]
To fix that I justf follow the instructions above (from @bilelwebdev and @leeivan ). 

**What I exactly did is following:**
 1. Added `"zendframework/zend-log": ">=2.3.0"` to `composer.json`.
 2. Run `composer update` or `php composer.phar update`.

Thanks!

**Comment by Doev** [comment]
Same here. ZFTool was not working before I added "zendframework/zend-log": ">=2.3.0" to composer.json.

**Comment by ezimuel** [comment]
I fixed this in the last merge, there was missing dependencies with Zend\Log and Zend\I18n due to the last update on zend-mvc.
